# Generated by Django 5.0.7 on 2024-08-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cedula',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'otro'), ('NA', 'Prefiero no decirlo')], max_length=20),
        ),
    ]
